app:
  name: AI Scientist
  version: 1.0.0

llm:
  provider: "qwen"
  model: "qwen-plus"
  temperature: 0.8
  max_tokens: 4096
  top_p: 0.95
  presence_penalty: 0.1
  frequency_penalty: 0.1

vector_store:
  persist_directory: "./data/chroma"
  collection_name: "research"
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  max_retries: 3
  retry_delay: 2
  disable_ssl_verification: false
  use_local_model: true
  local_model_path: "./models/embeddings"

database:
  url: sqlite:///research.db

redis:
  host: localhost
  port: 6379

agents:
  generator:
    enabled: true
    max_hypotheses: 5
    
  reflector:
    enabled: true
    evaluation_metrics:
      - novelty
      - feasibility
      - impact
      
  ranker:
    enabled: true
    ranking_criteria:
      - score
      - confidence
      
  evolver:
    enabled: true
    max_iterations: 3
    
  meta_reviewer:
    enabled: true
    review_frequency: 5
